[user]
name = "Davide Aversa"
email = "thek3nger@gmail.com"

[ui]
merge-editor = "vscode"
default-command = "log"

[git]
subprocess = true

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvVdJs4HZOaE/6qEPJ9Vb4TVyY1x3Jp9ZEpZLK2YlbK"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

## You can also use a path instead of embedding the key
# key = "~/.ssh/id_for_signing.pub"
